#A GENTE PODE IMPORTAR DE ARQUIVOS PYTHON, É SÓ ACHAR UMA BIBLIOTECA ONLINE COM OQ VC PRECISAR
#LINK: https://docs.python.org/3/py-modindex.html
#O CAMINHO PARA CHEGAR EH EXTERNAL LIBRARIES>LIB>EXTERNAL LINKS

"""
import
(.())
"""
